//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int Id { get; set; }
        public int Image { get; set; }
        public int AdId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual Ad Ad { get; set; }
    }
}
